version: '3.3'
services:
#  mysql:
#    image: mysql/mysql-server:5.7
#    container_name: mysql
#    ports:
#      - "3306:3306"
#    volumes:
#      - /usr/docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
#      - /usr/docker/mysql/initdb:/docker-entrypoint-initdb.d
#      - /usr/docker/mysql/data:/var/lib/mysql
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      - MYSQL_ROOT_PASSWORD=123456
#      - TZ=Asia/Shanghai
#    restart: always
#  redis:
#    image: 10.0.8.189/library/redis:5.0.3
#    container_name: redis
#    ports:
#      - "6379:6379"
#    restart: always
#    command: redis-server
#    volumes:
#      - /usr/docker/redis/data:/data
#    environment:
#      - TZ=Asia/Shanghai

#  redisManage:
#    image: 10.0.8.189/library/phpredisadmin:latest
#    container_name: redisManage
#    ports:
#      - "9001:80"
#    environment:
#      - REDIS_1_HOST=${IP}
#      - REDIS_1_NAME=redis
#    volumes:
#      - /etc/localtime:/etc/localtime:ro

  zookeeper:
    image: zookeeper:3.5.8
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /usr/docker/zookeeper/data:/data
      - /usr/docker/zookeeper/conf/zoo.cfg:/conf/zoo.cfg
      - /etc/localtime:/etc/localtime:ro
  kafka-0:
    image: docker.io/wurstmeister/kafka:2.12-2.4.1
    container_name: kafka-0
    restart: always
    ports:
      - "9090:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=10.33.80.102
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=0
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/kafka-0/data:/kafka/
      - /home/kafka-0/logs:/opt/kafka/logs
      - /etc/localtime:/etc/localtime:ro
  kafka-1:
    image: docker.io/wurstmeister/kafka
    container_name: kafka-1
    restart: always
    ports:
      - "9091:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=10.33.80.102
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/kafka-1/data:/kafka/
      - /home/kafka-1/logs:/opt/kafka/logs
      - /etc/localtime:/etc/localtime:ro
  kafka-2:
    image: docker.io/wurstmeister/kafka
    container_name: kafka-2
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=10.33.80.102
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/kafka-2/data:/kafka/
      - /home/kafka-2/logs:/opt/kafka/logs
      - /etc/localtime:/etc/localtime:ro
  kafkaManage:
    image: docker.io/sheepkiller/kafka-manager
    container_name: kafkaManage
    restart: always
    ports:
      - "9000:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
      - APPLICATION_SECRET=123456
    command: -Dpidfile.path=/dev/null
    volumes:
      - /etc/localtime:/etc/localtime:ro


