version: '3.3'
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql/my.cnf:/etc/my.cnf
      - /home/mysql/initdb:/docker-entrypoint-initdb.d
      - /home/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    restart: always
  redis:
    image: redis:5.0.3
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server
    volumes:
      - /home/redis/data:/data
    environment:
      - TZ=Asia/Shanghai

  redisManage:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: redisManage
    ports:
      - "9001:80"
    environment:
      - REDIS_1_HOST=10.33.80.102
      - REDIS_1_NAME=redis
    volumes:
      - /etc/localtime:/etc/localtime:ro

  ribbitmq:
    image: docker.io/rabbitmq:3.8.3-management
    container_name: ribbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro

  eureka:
    image: eureka
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - SPRING_PROFILES_ACTIVE=cli
      - EUREKA_INSTANCE_HOSTNAME=10.33.80.102
    volumes:
      - /etc/localtime:/etc/localtime:ro

  customer-api:
    image: customer-api
    container_name: customer-api
    ports:
      - "8083:8083"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - SPRING_PROFILES_ACTIVE=cli
      - EUREKA_INSTANCE_INSTANCE-ID=customer-api
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8761/eureka
      - SHARDING_JDBC_DATASOURCE_DS0_URL=jdbc:mysql://10.33.80.102:3306/pk2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      - SHARDING_JDBC_DATASOURCE_DS0_USERNAME=root
      - SHARDING_JDBC_DATASOURCE_DS0_PASSWORD=123456
      - SPRING_REDIS_HOST=10.33.80.102
      - SPRING_RABBITMQ_HOST=10.33.80.102
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro

  employee-api:
    image: employee-api
    container_name: employee-api
    ports:
      - "8086:8086"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - SPRING_PROFILES_ACTIVE=cli
      - EUREKA_INSTANCE_INSTANCE-ID=employee-api
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8761/eureka
      - SHARDING_JDBC_DATASOURCE_DS0_URL=jdbc:mysql://10.33.80.102:3306/pk2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      - SHARDING_JDBC_DATASOURCE_DS0_USERNAME=root
      - SHARDING_JDBC_DATASOURCE_DS0_PASSWORD=123456
      - SPRING_REDIS_HOST=10.33.80.102
      - SPRING_RABBITMQ_HOST=10.33.80.102
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro


  guardianship-api:
    image: guardianship-api
    container_name: guardianship-api
    ports:
      - "8085:8085"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - SPRING_PROFILES_ACTIVE=cli
      - EUREKA_INSTANCE_INSTANCE-ID=guardianship-api
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8761/eureka
      - SHARDING_JDBC_DATASOURCE_DS0_URL=jdbc:mysql://10.33.80.102:3306/pk2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      - SHARDING_JDBC_DATASOURCE_DS0_USERNAME=root
      - SHARDING_JDBC_DATASOURCE_DS0_PASSWORD=123456
      - SPRING_REDIS_HOST=10.33.80.102
      - SPRING_RABBITMQ_HOST=10.33.80.102
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro

  schedule-server:
    image: schedule
    container_name: schedule-server
    ports:
      - "8762:8762"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - SPRING_PROFILES_ACTIVE=cli
      - EUREKA_INSTANCE_INSTANCE-ID=schedule-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8761/eureka
      - SHARDING_JDBC_DATASOURCE_DS0_URL=jdbc:mysql://10.33.80.102:3306/pk2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      - SHARDING_JDBC_DATASOURCE_DS0_USERNAME=root
      - SHARDING_JDBC_DATASOURCE_DS0_PASSWORD=123456
      - SPRING_REDIS_HOST=10.33.80.102
      - SPRING_RABBITMQ_HOST=10.33.80.102
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro

  web-socket:
    image: web-socket
    container_name: web-socket
    ports:
      - "8087:8087"
      - "9999:9999"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - SPRING_PROFILES_ACTIVE=cli
      - SOCKETIO_SERVER_ORIGIN=http://10.33.80.102
      - SPRING_REDIS_HOST=10.33.80.102
      - SPRING_RABBITMQ_HOST=10.33.80.102
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro

  center-server:
    image: center
    container_name: center-server
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - SPRING_PROFILES_ACTIVE=cli
      - EUREKA_INSTANCE_INSTANCE-ID=center-server
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8761/eureka
      - SHARDING_JDBC_DATASOURCE_DS0_URL=jdbc:mysql://10.33.80.102:3306/pk2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      - SHARDING_JDBC_DATASOURCE_DS0_USERNAME=root
      - SHARDING_JDBC_DATASOURCE_DS0_PASSWORD=123456
      - SPRING_REDIS_HOST=10.33.80.102
      - SPRING_RABBITMQ_HOST=10.33.80.102
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro

  admin-api:
    image: admin-api
    container_name: admin-api
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - SPRING_PROFILES_ACTIVE=cli
      - EUREKA_INSTANCE_INSTANCE-ID=admin-api
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka:8761/eureka
      - SHARDING_JDBC_DATASOURCE_DS0_URL=jdbc:mysql://10.33.80.102:3306/pk2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      - SHARDING_JDBC_DATASOURCE_DS0_USERNAME=root
      - SHARDING_JDBC_DATASOURCE_DS0_PASSWORD=123456
      - SPRING_REDIS_HOST=10.33.80.102
      - SPRING_RABBITMQ_HOST=10.33.80.102
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro

  admin-web:
    image: admin-web
    container_name: admin-web
    ports:
      - "9090:80"
    volumes:
      - /home/service/admin-web/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro

  monitor-web:
    image: monitor-web
    container_name: monitor-web
    ports:
      - "9091:80"
    volumes:
      - /home/service/monitor-web/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro