version: '3.3'
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - /home/mysql/initdb:/docker-entrypoint-initdb.d
      - /home/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    restart: always
  redis:
    image: redis:5.0.3
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server
    volumes:
      - /home/redis/data:/data
    environment:
      - TZ=Asia/Shanghai

  redisManage:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: redisManage
    ports:
      - "9001:80"
    environment:
      - REDIS_1_HOST=${IP}
      - REDIS_1_NAME=redis
    volumes:
      - /etc/localtime:/etc/localtime:ro

  ribbitmq:
    image: docker.io/rabbitmq:3.8.3-management
    container_name: ribbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /etc/localtime:/etc/localtime:ro